CREATE TABLE ADMINISTRATOR (
	ID	NUMBER NOT NULL,
	PLACA	NUMBER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID) REFERENCES OSOBA(ID)
)

CREATE TABLE APTEKA (
	ID	NUMBER NOT NULL AUTO_INCREMENT,
	NAZWA	VARCHAR NOT NULL,
	GODZ_OD	NUMBER NOT NULL,
	GODZ_DO	NUMBER NOT NULL,
	ADRES	VARCHAR NOT NULL,
	TELEFON	NUMBER,
	PRIMARY KEY(ID)
)

CREATE TABLE DYZUR (
	DZIEN	VARCHAR NOT NULL,
	GODZ_OD	NUMBER NOT NULL,
	GODZ_DO	NUMBER NOT NULL,
	ID_FARMACEUTA	NUMBER NOT NULL,
	ID_APTEKA	NUMBER NOT NULL,
	CONSTRAINT DYZUR_PK PRIMARY KEY(ID_FARMACEUTA,ID_APTEKA),
	FOREIGN KEY(ID_APTEKA) REFERENCES APTEKA(ID),
	FOREIGN KEY(ID_FARMACEUTA) REFERENCES FARMACEUTA(ID)
)

CREATE TABLE FARMACEUTA (
	ID	NUMBER NOT NULL,
	PLACA	NUMBER NOT NULL,
	WYKSZTALCENIE	VARCHAR,
	PRIMARY KEY(ID),
	FOREIGN KEY (ID) REFERENCES OSOBA(ID)
)

CREATE TABLE KLIENT (
	ID	NUMBER,
	POPRZEDNI_ZAKUP	VARCHAR,
	PRIMARY KEY(ID)
	FOREIGN KEY (ID) REFERENCES OSOBA(ID)
)

CREATE TABLE LEKARSTWA (
	ILOSC	NUMBER NOT NULL,
	ID_ZAMOWIENIE	NUMBER NOT NULL,
	ID_LEKARSTWO	NUMBER NOT NULL,
	CONSTRAINT LEKARSTWA_PK PRIMARY KEY(ID_ZAMOWIENIE,ID_LEKARSTWO),
	FOREIGN KEY(ID_ZAMOWIENIE) REFERENCES ZAMOWIENIE(ID),
	FOREIGN KEY(ID_LEKARSTWO) REFERENCES LEK(ID)
)

CREATE TABLE LEK (
	ID	NUMBER NOT NULL AUTO_INCREMENT,
	NAZWA	VARCHAR NOT NULL,
	RECEPTA	BOOLEAN NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE MAGAZYN (
	POJEMNOSC NUMBER NOT NULL,
	ADRES	NUMBER NOT NULL,
	ID_APTEKA	NUMBER NOT NULL,
	ID_LEKARSTWO	NUMBER NOT NULL,
	CONSTRAINT LEKARSTWA_PK PRIMARY KEY(ID_APTEKA,ID_LEKARSTWO),
	FOREIGN KEY(ID_APTEKA) REFERENCES APTEKA(ID),
	FOREIGN KEY(ID_LEKARSTWO) REFERENCES LEK(ID)
)

CREATE TABLE MIASTO (
	ID	NUMBER NOT NULL AUTO_INCREMENT,
	NAZWA	VARCHAR NOT NULL,
	KOD	NUMBER NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE OSOBA (
	ID	NUMBER NOT NULL AUTO_INCREMENT,
	NAZWISKO	VARCHAR NOT NULL,
	IMIE	VARCHAR NOT NULL,
	DATA_URODZENIA	VARCHAR,
	TELEFON	NUMBER NOT NULL,
	EMAIL	VARCHAR,
	ADRES	VARCHAR,
	PRIMARY KEY(ID)
)

CREATE TABLE ZAMOWIENIE (
	ID	NUMBER NOT NULL AUTO_INCREMENT,
	STATUS	VARCHAR NOT NULL,
	DATA_ZAMOWIENIA	VARCHAR NOT NULL,
	PRIMARY KEY(ID)
)

DELIMITER $$

CREATE OR REPLACE PROCEDURE Nowy_zakop
	(klient_ID IN NUMBER
	date IN VARCHAR)
BEGIN
	UPDATE KLIENT
	SET POPRZEDNI_ZAKUP = date
	WHERE klient_ID = ID;
	INSERT INTO ZAMOWIENIE
	(STATUS, DATA_ZAMOWIENIA)
	VALUES('DO REALIZACJI', date);
END$$
DELIMITER ;


DELIMITER $$

CREATE OR REPLACE FUNCTION suma_plac
	RETURNS NUMBER
BEGIN
	DECLARE vSum NUMBER;
	vSum = (SELECT SUM(PLACA) FROM FARMACEUTA) + (SELECT SUM(PLACA) FROM ADMINISTRATOR);
	RETURN (vSum);

END$$
DELIMITER ;
	