CREATE TABLE OSOBA (
	ID	int NOT NULL AUTO_INCREMENT,
	NAZWISKO	VARCHAR(20) NOT NULL,
	IMIE	VARCHAR(20) NOT NULL,
	DATA_URODZENIA	VARCHAR(20),
	TELEFON	int NOT NULL,
	EMAIL	VARCHAR(20),
	ADRES	VARCHAR(30),
	PRIMARY KEY(ID)
);

CREATE TABLE ADMINISTRATOR (
	ID	int NOT NULL,
	PLACA	int NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID) REFERENCES OSOBA(ID)
);

CREATE TABLE APTEKA (
	ID	int NOT NULL AUTO_INCREMENT,
	NAZWA	VARCHAR(20) NOT NULL,
	GODZ_OD	int NOT NULL,
	GODZ_DO	int NOT NULL,
	ADRES	VARCHAR(30) NOT NULL,
	TELEFON	int,
	PRIMARY KEY(ID)
);

CREATE TABLE FARMACEUTA (
	ID	int NOT NULL,
	PLACA	int NOT NULL,
	WYKSZTALCENIE	VARCHAR(20),
	PRIMARY KEY(ID),
	FOREIGN KEY (ID) REFERENCES OSOBA(ID)
);

CREATE TABLE DYZUR (
	DZIEN	VARCHAR(20) NOT NULL,
	GODZ_OD	int NOT NULL,
	GODZ_DO	int NOT NULL,
	ID_FARMACEUTA	int NOT NULL,
	ID_APTEKA	int NOT NULL,
	CONSTRAINT DYZUR_PK PRIMARY KEY(ID_FARMACEUTA,ID_APTEKA, DZIEN),
	FOREIGN KEY(ID_APTEKA) REFERENCES APTEKA(ID),
	FOREIGN KEY(ID_FARMACEUTA) REFERENCES FARMACEUTA(ID)
);

CREATE TABLE KLIENT (
	ID	int,
	POPRZEDNI_ZAKUP	VARCHAR(20),
	PRIMARY KEY(ID),
	FOREIGN KEY (ID) REFERENCES OSOBA(ID)
);

CREATE TABLE LEK (
	ID	int NOT NULL AUTO_INCREMENT,
	NAZWA	VARCHAR(20) NOT NULL,
	RECEPTA	BOOLEAN NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ZAMOWIENIE (
	ID	int NOT NULL AUTO_INCREMENT,
	STATUS	VARCHAR(20) NOT NULL,
	ID_KLIENT int not NULL,
	DATA_ZAMOWIENIA	VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_KLIENT) REFERENCES KLIENT(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE LEKARSTWA (
	ILOSC	int NOT NULL,
	ID_ZAMOWIENIE	int NOT NULL,
	ID_LEKARSTWO	int NOT NULL,
	CONSTRAINT LEKARSTWA_PK PRIMARY KEY(ID_ZAMOWIENIE,ID_LEKARSTWO),
	FOREIGN KEY(ID_ZAMOWIENIE) REFERENCES ZAMOWIENIE(ID),
	FOREIGN KEY(ID_LEKARSTWO) REFERENCES LEK(ID)
);

CREATE TABLE MAGAZYN (
	POJEMNOSC int NOT NULL,
	ADRES	VARCHAR(30) NOT NULL,
	ID_APTEKA	int NOT NULL,
	ID_LEKARSTWO	int NOT NULL,
	CONSTRAINT LEKARSTWA_PK PRIMARY KEY(ID_APTEKA,ID_LEKARSTWO),
	FOREIGN KEY(ID_APTEKA) REFERENCES APTEKA(ID),
	FOREIGN KEY(ID_LEKARSTWO) REFERENCES LEK(ID)
);

CREATE TABLE MIASTO (
	ID	int NOT NULL AUTO_INCREMENT,
	NAZWA	VARCHAR(20) NOT NULL,
	KOD	VARCHAR(6) NOT NULL,
	PRIMARY KEY(ID)
);

DELIMITER $$

CREATE OR REPLACE PROCEDURE Nowy_zakop
	(IN klient_ID int,
	IN new_date VARCHAR(10))
BEGIN
	UPDATE KLIENT
	SET POPRZEDNI_ZAKUP = new_date
	WHERE ID = klient_ID;
	INSERT INTO ZAMOWIENIE
	(STATUS, DATA_ZAMOWIENIA, ID_KLIENT)
	VALUES("DO REALIZACJI", new_date, klient_ID);
END$$
DELIMITER ;